### PR TITLE
Allow for SQUID_VERSION and auto detect latest

### PR DESCRIPTION
**Pull request by EnorMOZ**

### CODE REVIEW

**Comment by elico** [comment]
@EnorMOZ I have just seen the commit.
There is a better way to "auto detect latest" however I need to find the ruby script I have used to do that.
I will try to find it in the next couple days and will respond.

If you see no respond here try to bump this.

**Comment by EnorMOZ** [comment]
@elico I was trying to keep it simple without having to use or install any external programs or modules. Ideally this would be fixed upstream on the squid-cache release side.

**Comment by elico** [comment]
@EnorMOZ Can you open a bug about this in the Squid-Cache bugzille?
https://bugs.squid-cache.org/index.cgi

**Comment by elico** [comment]
The code to fetch the latest version of squid is in the repo:
https://github.com/elico/squid-latest

And this repo is being updated automatically.

**Pull request closed without merging**
